import type { Metadata } from "next";
import "./globals.css";
import { switzer } from "./fonts";
import MainLayout from "@/layout/main";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={switzer.variable + " font-switzer bg-white"}>
        <main>
          <MainLayout>{children}</MainLayout>
        </main>
      </body>
    </html>
  );
}
